name: Mirror to Codeberg

on:
  push:
    branches:
      - "**"
    tags:
      - "**"
  delete:
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Start SSH agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.CODEBERG_SSH_KEY }}

      - name: Trust Codeberg host key
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan codeberg.org >> ~/.ssh/known_hosts

      - name: Show loaded SSH keys
        run: |
          ssh-add -l
          ssh-add -L

      - name: Mirror repository
        run: |
          git clone --bare https://github.com/${{ github.repository }}.git repo.git
          cd repo.git
          git remote add codeberg git@codeberg.org:shorinkiwata/shorin-arch-setup.git
          git push --prune codeberg 'refs/heads/*:refs/heads/*'
          git push --prune codeberg 'refs/tags/*:refs/tags/*'
